---
- name: Update apt cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  become: yes

- name: Upgrade all packages
  apt:
    upgrade: dist
    force_apt_get: yes
  become: yes

- name: Refresh sudo token
  become: yes
  ansible.builtin.command: echo "Sudo refreshed"

- name: Install required tools
  apt:
    name:
      - build-essential
      - colorized-logs
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - rsyslog
      - ufw
      - libreadline-dev
      - libsqlite3-dev
      - highlight
      - gdb
      - caido
      - caido-cli
      - mingw-w64
      - fonts-firacode
      - wget
      - curl
      - llvm
      - make
      - cmake
      - qt6-base-dev
      - qt6-base-private-dev
      - libxkbcommon-dev
      - qt6-websockets-dev
      - qt6-declarative-dev
      - gcc 
      - g++
      - g++-mingw-w64
      - libncurses5-dev
      - zsh
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - libfuse2
      - gron
      - network-manager
      - binwalk
      - foremost
      - hexedit
      - cargo
      - unzip
      - tar
      - unrar
      - httpie
      - zip
      - autorecon
      - vim
      - libxml2-dev
      - libxmlsec1-dev
      - libguestfs-tools
      - libpoppler-cpp-dev
      - ltrace
      - net-tools
      - openjdk-21-jdk
      - openjdk-21-jre
      - p7zip-full
      - poppler-utils
      - reglookup
      - sqlite3-tools
      - tshark
      - jq
      - pipx
      - ntpsec-ntpdate
      - krb5-user
      - flameshot
      - exiftool
      - tmux
      - ruby-rubygems
      - ruby
      - freerdp3-x11
      - impacket-scripts
      - netexec
      - responder
      - wpscan
      - evil-winrm
      - metasploit-framework
      - msfpc
      - shellter
      - whatweb
      - mimikatz
      - python3-pypykatz
      - kerberoast
      - golang-go
      - python3-minikerberos
      - bloodyad
      - smbmap
      - feroxbuster
      - dirsearch
    state: latest
    force_apt_get: yes
  become: yes

- name: Refresh sudo token
  become: yes
  ansible.builtin.command: echo "Sudo refreshed"

- name: Clean up unused packages
  apt:
    autoclean: yes
  become: yes

- name: Remove unnecessary packages
  apt:
    autoremove: yes
  become: yes
