- name: Ensure /opt/Tools directory exists
  file:
    path: /opt/Tools
    state: directory
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    mode: '0755'
  become: true

- name: Refresh sudo token (if needed)
  become: true
  ansible.builtin.command: whoami

- name: Compile BloodHound-CLI
  shell: |
    set -e
    go build -ldflags="-s -w -X 'github.com/SpecterOps/BloodHound_CLI/cmd/config.Version=`git describe --tags --abbrev=0`' -X 'github.com/SpecterOps/BloodHound_CLI/cmd/config.BuildDate=`date -u '+%d %b %Y'`'" -o bloodhound-cli main.go
  args:
    chdir: /opt/Tools/Bloodhound-cli
  register: build_bh
  failed_when: build_bh.rc != 0
  changed_when: "'bloodhound-cli' in build_bh.stdout or build_bh.rc == 0"

- name: Determine home directory for the runtime user
  ansible.builtin.shell: "getent passwd '{{ ansible_user_id }}' | cut -d':' -f6"
  register: user_home_cmd
  changed_when: false
  failed_when: user_home_cmd.rc != 0

- name: Set user_home fact
  ansible.builtin.set_fact:
    user_home: "{{ user_home_cmd.stdout }}"

- name: Ensure user's go bin dir exists
  file:
    path: "{{ user_home }}/go/bin"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  become: true

- name: Install bloodhound-cli into user's go bin
  copy:
    remote_src: yes
    src: /opt/Tools/Bloodhound-cli/bloodhound-cli
    dest: "{{ user_home }}/go/bin/bloodhound-cli"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
    force: yes
  become: true
