---
- name: Ensure /opt/Tools directory exists
  file:
    path: /opt/Tools
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'
  become: true

- name: Refresh sudo token
  become: yes
  ansible.builtin.command: echo "Sudo refreshed"

- name: Clone GitHub repositories
  git:
    repo: "{{ item.repo }}"
    dest: "/opt/Tools/{{ item.name }}"
    recursive: "{{ item.recursive | default(false) }}"
  loop:
    - { repo: "https://github.com/DidierStevens/DidierStevensSuite", name: "DidierStevensSuite" }
    - { repo: "https://github.com/danielbohannon/Invoke-Obfuscation", name: "Invoke-Obfuscation" }
    - { repo: "https://github.com/rasta-mouse/Sherlock", name: "Sherlock" }
    - { repo: "https://github.com/PowerShellMafia/PowerSploit", name: "PowerSploit" }
    - { repo: "https://github.com/samratashok/nishang", name: "nishang" }
    - { repo: "https://github.com/honze-net/nmap-bootstrap-xsl", name: "nmap-bootstrap-xsl" }
    - { repo: "https://github.com/sqlmapproject/sqlmap", name: "sqlmap" }
    - { repo: "https://github.com/RUB-NDS/PRET", name: "PRET" }
    - { repo: "https://github.com/peass-ng/PEASS-ng", name: "PEASS-ng" }
    - { repo: "https://github.com/joey-melo/netcredz", name: "netcredz" }
    - { repo: "https://github.com/AlmondOffSec/PassTheCert", name: "PassTheCert" }
    - { repo: "https://github.com/topotam/PetitPotam", name: "PetitPotam" }
    - { repo: "https://github.com/nicocha30/ligolo-ng", name: "ligolo-ng" }
    - { repo: "https://github.com/ropnop/windapsearch", name: "windapsearch" }
    - { repo: "https://github.com/danielmiessler/SecLists", name: "SecLists" }
    - { repo: "https://github.com/ShutdownRepo/pywhisker", name: "pywhisker" }
    - { repo: "https://github.com/dirkjanm/PKINITtools", name: "PKINITtools" }
    - { repo: "https://github.com/JohnHammond/binnim", name: "binnim" }

- name: Build ligolo-ng binaries
  shell: |
    go build -o agent cmd/agent/main.go
    go build -o proxy cmd/proxy/main.go
    GOOS=windows go build -o agent.exe cmd/agent/main.go
    GOOS=windows go build -o proxy.exe cmd/proxy/main.go
  args:
    chdir: /opt/Tools/ligolo-ng

- name: Build nim
  shell: |
    echo "Installig nim"
    curl https://nim-lang.org/choosenim/init.sh -sSf | sh
  args:
    executable: /bin/bash

- name: Build binnim binary
  shell: |
    nimble build
    nimble install
  args:
    chdir: /opt/Tools/binnim

# Allows current user to own tools directory
- name: Ensure current user owns all files in /opt/Tools
  file:
    path: /opt/Tools
    state: directory
    recurse: yes
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'
  become: true
