---
# Install Node.js
- name: Get latest Node.js version
  shell: |
    node_version=$(curl -sn https://nodejs.org/dist/latest/ | grep -Eo 'node-v[0-9]+\.[0-9]+\.[0-9]+-linux-x64\.tar\.xz' | sort -u)
    wget https://nodejs.org/dist/latest/$node_version
    mkdir -p /usr/local/lib/nodejs
    tar -xJvf $node_version -C /usr/local/lib/nodejs
    rm -rf $node_version
  args:
    executable: /bin/bash
  become: true