---
- name: Update package cache
  apt:
    update_cache: yes
  become: true

- name: Fix broken or missing packages
  command: apt-get -f install -y
  register: fix_missing_output
  changed_when: "'0 upgraded, 0 newly installed' not in fix_missing_output.stdout"
  become: true

- name: Add Microsoft package repository for PowerShell
  shell: |
    . /etc/os-release
    wget -q https://packages.microsoft.com/config/ubuntu/${VERSION_ID}/packages-microsoft-prod.deb
    dpkg -i packages-microsoft-prod.deb
    rm -f packages-microsoft-prod.deb
  args:
    executable: /bin/bash
  become: true

- name: Install PowerShell
  apt:
    name: powershell
    state: present
  become: true

- name: Set timezone to New York
  file:
    src: /usr/share/zoneinfo/America/New_York
    dest: /etc/localtime
    state: link
  become: true

- name: Reconfigure timezone data
  command: dpkg-reconfigure --frontend noninteractive tzdata
  become: true

- name: Clean up unused packages
  apt:
    autoclean: yes
    autoremove: yes
  become: true