---
- name: Ensure Python and pip are installed
  apt:
    name:
      - python3
      - python3-pip
      - pipx
    state: present
  become: true

- name: Install pipx if not already installed
  shell: sudo apt-get install -y pipx
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  when: "'pipx' not in lookup('env', 'PATH')"

- name: Ensure pipx path is in user environment
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:~/.local/bin'
    state: present

- name: Source bashrc to update environment
  shell: source ~/.bashrc
  args:
    executable: /bin/bash

- name: Install tools using pipx
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  loop:
    - mitmproxy2swagger
    - arjun
    - xlsxgrep
    - certipy-ad