---
- name: Ensure Python and pip are installed
  apt:
    name:
      - python3
      - python3-pip
      - pipx
    state: present
  become: true

- name: Ensure pipx path is in user environment
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:~/.local/bin'
    state: present

- name: Source bashrc to update environment
  shell: source ~/.bashrc
  args:
    executable: /bin/bash

- name: Install tools using pipx
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  loop:
    - xlsxgrep
    - certipy-ad
    - evil-winrm-py