- name: Print current user (debug)
  shell: whoami
  register: current_user

- debug:
    msg: "Installing as user: {{ current_user.stdout }}"

- name: Install Oh My Zsh and plugins
  shell: |
    export ZSH_CUSTOM="${HOME}/.oh-my-zsh/custom"
    export HOME="${HOME}"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    git clone https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
    git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-history-substring-search $ZSH_CUSTOM/plugins/zsh-history-substring-search
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ lookup('env', 'HOME') }}"
    USER: "{{ lookup('env', 'USER') }}"
    SHELL: "/bin/zsh"