---
- name: Offensive Security Toolkit
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    #- role: "roles/configure-tmux"
    #- role: "roles/customize-terminal"
    #- role: "roles/customize-browser"
    #- role: "roles/configure-logging"
    #- role: "roles/configure-system"
    - role: gantsign.visual-studio-code
      vars:
        users:
          - username: "{{ ansible_user_id }}"
            visual_studio_code_extensions:
              - ms-python.python
              - snyk-security.snyk-vulnerability-scanner
