---
- name: Offensive Ansible - System Configuration
  hosts: localhost
  connection: local
  become: false
  gather_facts: true

  pre_tasks:
    - name: Ensure system is Kali Linux
      fail:
        msg: "❌ This playbook only supports Kali Linux!"
      when: ansible_distribution != "Kali"

  roles:
    - role: "roles/install-tools"
    - role: "roles/configure-tmux"
    - role: "roles/configure-logging"
    - role: "roles/customize-terminal"

- name: Install Visual Studio Code Extensions (non-root)
  hosts: localhost
  connection: local
  become: false
  gather_facts: true

  roles:
    - role: gantsign.visual-studio-code
      vars:
        users:
          - username: "{{ ansible_user_id }}"
            visual_studio_code_extensions:
              - ms-python.python
              - snyk-security.snyk-vulnerability-scanner