---
# Detect GNOME Terminal
- name: Detect GNOME Terminal
  command: gsettings list-schemas
  register: gnome_terminal_check
  changed_when: false

# Install GNOME Terminal tools
- name: Install GNOME Terminal tools
  package:
    name: gnome-shell
    state: present
  when: "'org.gnome.desktop.interface' in gnome_terminal_check.stdout"

# Set GNOME Terminal font
- name: Set GNOME Terminal font to FiraCode
  command: gsettings set org.gnome.desktop.interface monospace-font-name "Fira Code Regular 12"
  when: "'org.gnome.desktop.interface' in gnome_terminal_check.stdout"

# Detect XFCE Terminal
- name: Detect XFCE Terminal
  command: xfconf-query -l
  register: xfce_terminal_check
  changed_when: false

# Install XFCE Terminal tools
- name: Install XFCE Terminal tools
  package:
    name: xfconf
    state: present
  when: "'/terminal/font' in xfce_terminal_check.stdout"

# Set XFCE Terminal font
- name: Set XFCE Terminal font to FiraCode
  command: xfconf-query -c xfce4-terminal -p /terminal/font -s "Fira Code 12"
  when: "'/terminal/font' in xfce_terminal_check.stdout"

# Detect Alacritty
- name: Detect Alacritty
  stat:
    path: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
  register: alacritty_check

# Ensure Alacritty config directory exists
- name: Ensure Alacritty config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory
    mode: '0755'
  when: alacritty_check.stat.exists == false

# Set Alacritty font to FiraCode
- name: Configure Alacritty font to FiraCode
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
    block: |
      font:
        family: "Fira Code"
        size: 12.0
  when: alacritty_check.stat.exists

# Install common tools (unzip for font handling)
- name: Ensure unzip is installed
  package:
    name: unzip
    state: present
  when: alacritty_check.stat.exists or
        "'org.gnome.desktop.interface' in gnome_terminal_check.stdout or
        '/terminal/font' in xfce_terminal_check.stdout"

# Catch-all for unsupported terminals
- name: Notify unsupported terminal
  debug:
    msg: "No supported terminal emulator detected. Skipping font configuration."
  when: >
    "'org.gnome.desktop.interface' not in gnome_terminal_check.stdout and
    '/terminal/font' not in xfce_terminal_check.stdout and
    alacritty_check.stat.exists == false"
