---
- name: "Copy ZSHRC"
  copy:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_env.HOME }}"

- name: "Copy ZSH theme"
  copy:
    src: "{{ role_path }}/files/steve0ro.zsh-theme"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/themes/"