---
- name: Checks if tmux directory exists
  file:
    path: "{{ ansible_env.HOME }}/.tmux"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'

- name: Checks if Logs directory exists
  file:
    path: "{{ ansible_env.HOME }}/Logs"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'

- name: Copying Tmux Config
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0644'

- name: Tmux logging script
  copy:
    src: "{{ role_path }}/files/tmux_logging.sh"
    dest: "{{ ansible_env.HOME }}/.tmux/tmux_logging.sh"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'
