- name: "Install Packages"
  package:
    name: "auditd"
    state: present  
  become: true
  become_method: sudo

- name: "Configure Audit Rules"
  copy:
    src: audit.rules
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: 0640      
  become: true
  become_method: sudo

- name: "Create _laurel user"
  user:
    name: _laurel
    state: present
    shell: /bin/false
    create_home: no
    home: /var/log/laurel
  become: true
  become_method: sudo

- name: "Create directories for _laurel /var/log/laurel"
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0750') }}"
  loop:
    - { "path": "/var/log/laurel", "owner": "_laurel", "group": "_laurel" }
    - { "path": "/tmp/laurel", "owner": "_laurel", "group": "_laurel" }
    - { "path":"/etc/laurel" }
  become: true
  become_method: sudo
  async: 15
  poll: 0

- name: "Copy laurel/config.toml to /etc/laurel/config.toml"
  copy:
    src: laurel/config.toml
    dest: /etc/laurel/config.toml
    owner: _laurel
    group: _laurel
    mode: 0640
  become: true
  become_method: sudo

- name: "Copy laurel/laurel.conf to /etc/audit/plugins.d"
  copy:
    src: laurel/laurel.conf
    dest: /etc/audit/plugins.d/laurel.conf
    owner: root
    group: root
    mode: 0640
  become: true
  become_method: sudo

- name: "Download and extract Laurel via bash script"
  shell: |
    set -e

    LAUREL_URL="https://github.com/threathunters-io/laurel/releases/download/v0.5.2/laurel-v0.5.2-x86_64-glibc.tar.gz"
    ARCHIVE_PATH="/tmp/laurel-v0.5.2-x86_64-glibc.tar.gz"
    EXTRACT_DIR="/tmp/laurel"

    echo "Downloading Laurel..."
    curl -L "$LAUREL_URL" -o "$ARCHIVE_PATH"

    echo "Extracting Laurel..."
    mkdir -p "$EXTRACT_DIR"
    tar -xzf "$ARCHIVE_PATH" -C "$EXTRACT_DIR"

    echo "Setting permissions..."
    chown -R root:root "$EXTRACT_DIR"
    chmod -R 0755 "$EXTRACT_DIR"
  args:
    executable: /bin/bash
  become: true
  tags: laurel


- name: "Running install -m755 laurel /usr/local/sbin/laurel"
  command: "install -m755 laurel /usr/local/sbin/laurel"
  args:
    chdir: /tmp/laurel/
  become: true
  become_method: sudo
  
- name: "Restart auditd"
  service:
    name: auditd
    state: restarted
  become: true
  become_method: sudo

